#!/bin/bash

# Usage: ./chromedrv-install <VERSION>

set -e

DRV_VER=${1:-'2.40'}

cd /tmp
wget https://chromedriver.storage.googleapis.com/$DRV_VER/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
mv chromedriver /usr/local/bin/