#!/bin/bash
set -e

apt-get install postgresql postgresql-contrib libpq-dev -y

service postgresql start && sudo -u postgres psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  UPDATE pg_database SET datistemplate=FALSE WHERE datname='template1';
  DROP DATABASE template1;
  CREATE DATABASE template1 WITH owner=postgres template=template0 encoding='UTF8';
  UPDATE pg_database SET datistemplate=TRUE WHERE datname='template1';
  ALTER USER postgres WITH PASSWORD 'postgres';
EOSQL