AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/**/*
    - config/**/*
    - log/**/*
    - tmp/**/*
    - bin/**/*
    - node_modules/**/*

Metrics/LineLength:
  Max: 125

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/GuardClause:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false