version: '3'
services:
  postgres:
    image: postgres:10
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data
    volumes:
      - .docker/data/postgresql:/data
  redis:
    image: redis:4.0.10
    ports:
      - 6381:6379
    volumes:
      - .docker/data/redis:/data
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    command: ngrok http docker.for.mac.localhost:3000 -log stdout